import Head from "next/head";
import Header from "components/Header/header";
import Loader from "components/Loader/loader";
import styles from '@/styles/Calculator.module.css';
import Footer from "components/Footer/footer";
export default function Caclulator() {
    return(
        <>
        <Head>
        <title>Leberkasrechner</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
       <main>
        <Loader></Loader>
        <Header></Header>
        <h1 className={styles.Headline}>
        Wie viele Leberkassemmeln hast du?
          </h1>
        <div className={styles.Calculator}>
        <input className="form-control" placeholder="Anzahl eingeben"></input>
       </div>
       <Footer></Footer>
       </main>

        </>
    )
}